/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWhitelistRouteImport } from './routes/_app.whitelist'
import { Route as AppStatisticsRouteImport } from './routes/_app.statistics'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppKeysRouteImport } from './routes/_app.keys'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppScriptsIndexRouteImport } from './routes/_app.scripts.index'
import { Route as AppScriptsAddRouteImport } from './routes/_app.scripts.add'
import { Route as AppScriptsIdRouteImport } from './routes/_app.scripts.$id'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWhitelistRoute = AppWhitelistRouteImport.update({
  id: '/whitelist',
  path: '/whitelist',
  getParentRoute: () => AppRoute,
} as any)
const AppStatisticsRoute = AppStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppKeysRoute = AppKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppScriptsIndexRoute = AppScriptsIndexRouteImport.update({
  id: '/scripts/',
  path: '/scripts/',
  getParentRoute: () => AppRoute,
} as any)
const AppScriptsAddRoute = AppScriptsAddRouteImport.update({
  id: '/scripts/add',
  path: '/scripts/add',
  getParentRoute: () => AppRoute,
} as any)
const AppScriptsIdRoute = AppScriptsIdRouteImport.update({
  id: '/scripts/$id',
  path: '/scripts/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/dashboard': typeof AppDashboardRoute
  '/keys': typeof AppKeysRoute
  '/settings': typeof AppSettingsRoute
  '/statistics': typeof AppStatisticsRoute
  '/whitelist': typeof AppWhitelistRoute
  '/scripts/$id': typeof AppScriptsIdRoute
  '/scripts/add': typeof AppScriptsAddRoute
  '/scripts/': typeof AppScriptsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/dashboard': typeof AppDashboardRoute
  '/keys': typeof AppKeysRoute
  '/settings': typeof AppSettingsRoute
  '/statistics': typeof AppStatisticsRoute
  '/whitelist': typeof AppWhitelistRoute
  '/scripts/$id': typeof AppScriptsIdRoute
  '/scripts/add': typeof AppScriptsAddRoute
  '/scripts': typeof AppScriptsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/access-denied': typeof AccessDeniedRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/keys': typeof AppKeysRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/statistics': typeof AppStatisticsRoute
  '/_app/whitelist': typeof AppWhitelistRoute
  '/_app/scripts/$id': typeof AppScriptsIdRoute
  '/_app/scripts/add': typeof AppScriptsAddRoute
  '/_app/scripts/': typeof AppScriptsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-denied'
    | '/login'
    | '/pricing'
    | '/dashboard'
    | '/keys'
    | '/settings'
    | '/statistics'
    | '/whitelist'
    | '/scripts/$id'
    | '/scripts/add'
    | '/scripts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-denied'
    | '/login'
    | '/pricing'
    | '/dashboard'
    | '/keys'
    | '/settings'
    | '/statistics'
    | '/whitelist'
    | '/scripts/$id'
    | '/scripts/add'
    | '/scripts'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/access-denied'
    | '/login'
    | '/pricing'
    | '/_app/dashboard'
    | '/_app/keys'
    | '/_app/settings'
    | '/_app/statistics'
    | '/_app/whitelist'
    | '/_app/scripts/$id'
    | '/_app/scripts/add'
    | '/_app/scripts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AccessDeniedRoute: typeof AccessDeniedRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/whitelist': {
      id: '/_app/whitelist'
      path: '/whitelist'
      fullPath: '/whitelist'
      preLoaderRoute: typeof AppWhitelistRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/statistics': {
      id: '/_app/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof AppStatisticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/keys': {
      id: '/_app/keys'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof AppKeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scripts/': {
      id: '/_app/scripts/'
      path: '/scripts'
      fullPath: '/scripts/'
      preLoaderRoute: typeof AppScriptsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scripts/add': {
      id: '/_app/scripts/add'
      path: '/scripts/add'
      fullPath: '/scripts/add'
      preLoaderRoute: typeof AppScriptsAddRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scripts/$id': {
      id: '/_app/scripts/$id'
      path: '/scripts/$id'
      fullPath: '/scripts/$id'
      preLoaderRoute: typeof AppScriptsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppKeysRoute: typeof AppKeysRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStatisticsRoute: typeof AppStatisticsRoute
  AppWhitelistRoute: typeof AppWhitelistRoute
  AppScriptsIdRoute: typeof AppScriptsIdRoute
  AppScriptsAddRoute: typeof AppScriptsAddRoute
  AppScriptsIndexRoute: typeof AppScriptsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppKeysRoute: AppKeysRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStatisticsRoute: AppStatisticsRoute,
  AppWhitelistRoute: AppWhitelistRoute,
  AppScriptsIdRoute: AppScriptsIdRoute,
  AppScriptsAddRoute: AppScriptsAddRoute,
  AppScriptsIndexRoute: AppScriptsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AccessDeniedRoute: AccessDeniedRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
